# Generated by Django 4.2.25 on 2025-10-31 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workers', '0003_remove_worker_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_slot', models.CharField(blank=True, choices=[('07:00-09:00', '07:00-09:00'), ('09:00-11:00', '09:00-11:00'), ('11:00-13:00', '11:00-13:00'), ('13:00-15:00', '13:00-15:00'), ('15:00-17:00', '15:00-17:00'), ('17:00-19:00', '17:00-19:00'), ('19:00-21:00', '19:00-21:00'), ('21:00-23:00', '21:00-23:00'), ('23:00-01:00', '23:00-01:00'), ('01:00-03:00', '01:00-03:00'), ('03:00-05:00', '03:00-05:00'), ('05:00-07:00', '05:00-07:00')], help_text='Time slot for guarding tasks. Leave empty for full-day tasks.', max_length=20, null=True)),
                ('task_type', models.CharField(choices=[('patrol_a', 'Patrol A'), ('patrol_b', 'Patrol B'), ('kitchen', 'Kitchen')], max_length=50)),
                ('is_commander', models.BooleanField(default=False, help_text='Indicates if this worker is the commander for this patrol assignment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.worker')),
            ],
            options={
                'ordering': ['date', 'time_slot', 'task_type'],
                'unique_together': {('date', 'time_slot', 'task_type', 'worker')},
            },
        ),
    ]
