# Generated by Django 4.2.25 on 2025-10-31 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='task_type',
            field=models.CharField(choices=[('guard_duty', 'Guard Duty'), ('patrol_a', 'Patrol A'), ('patrol_b', 'Patrol B'), ('kitchen', 'Kitchen')], max_length=50),
        ),
    ]
