# Generated by Django 4.2.25 on 2025-11-01 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_remove_worker_group'),
        ('assignments', '0002_alter_assignment_task_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('guard_duty', 'Guard Duty'), ('patrol_a', 'Patrol A'), ('patrol_b', 'Patrol B'), ('kitchen', 'Kitchen')], max_length=50)),
                ('position', models.IntegerField(default=0, help_text='Queue position (0 = first in line)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_queues', to='workers.worker')),
            ],
            options={
                'ordering': ['task_type', 'position'],
                'indexes': [models.Index(fields=['task_type', 'position'], name='assignments_task_ty_baddac_idx')],
                'unique_together': {('worker', 'task_type')},
            },
        ),
    ]
