# Generated by Django 4.2.25 on 2025-10-31 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('hard_chores_counter', models.IntegerField(default=0)),
                ('outer_partner_counter', models.IntegerField(default=0)),
                ('group', models.CharField(blank=True, choices=[('kitchen', 'Kitchen'), ('patrol_a', 'Patrol A'), ('patrol_b', 'Patrol B')], max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
