# Generated by Django 4.2.25 on 2025-10-31 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='title',
            field=models.CharField(choices=[('commander', 'Commander'), ('soldier', 'Soldier')], max_length=50),
        ),
    ]
