# Generated by Django 4.2.25 on 2025-10-31 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_alter_worker_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='group',
        ),
    ]
